name: deploy-system

inputs:
  github-token:
    description: |
      GitHub token for creating releases. GITHUB_TOKEN is set for every action
      and can be passed as an input to this action. You will also need to set
      the `contents: write` permission for the token.

      See docs for more info:
      * https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-github-cli-in-workflows
      * https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token 
    required: true

runs:
  using: composite
  steps:
    - name: Restore cache
      uses: actions/cache/restore@v4
      with:
        path: deploy/system
        key: deploy/system-${{ github.sha }}-${{ github.ref_name }}
    - name: Create release notes
      shell: bash
      run: |
        export REF_NAME=$(echo "${{ github.ref_name }}" | sed 's,[\\\^\$\.\|\?\*\+\(\)\[\]]*,\\\0,g')
        grep -Pazo "(?s)(?<=## ${REF_NAME})[^#]+" deploy/system/CHANGELOG.md | sed '/./,$!d' | tr -d '\0' > deploy/system/RELEASE_NOTES
        echo "$(< deploy/system/RELEASE_NOTES)"
    - name: Deploy artifacts to Github
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        gh release create ${{ github.ref_name }} deploy/system/artifacts/* --title ${{ github.ref_name }} -F deploy/system/RELEASE_NOTES --draft
