name: deploy-system

runs:
  using: composite
  steps:
    - name: Restore cache
      uses: actions/cache/restore@v4
      with:
        path: deploy/system
        key: deploy/system-${{ github.sha }}-${{ github.ref_name }}
    - name: Create release notes
      shell: bash
      run: |
        export REF_NAME=$(echo "${{ github.ref_name }}" | sed 's,[\\\^\$\.\|\?\*\+\(\)\[\]]*,\\\0,g')
        grep -Pazo "(?s)(?<=## ${REF_NAME})[^#]+" deploy/system/CHANGELOG.md | sed '/./,$!d' | tr -d '\0' > deploy/system/RELEASE_NOTES
        echo "$(< deploy/system/RELEASE_NOTES)"
    - name: Deploy artifacts to Github
      shell: bash
      run: |
        gh release create ${{ github.ref_name }} deploy/system/artifacts --title ${{ github.ref_name }} -F deploy/system/RELEASE_NOTES --draft
