name: install-ghr

inputs:
  version:
    required: false
    default: 0.16.2

runs:
  using: composite
  steps:
    - name: Install ghr
      shell: bash
      run: |
        wget -nv https://github.com/tcnksm/ghr/releases/download/v${{ inputs.version }}/ghr_v${{ inputs.version }}_linux_amd64.tar.gz
        tar xf ghr_v${{ inputs.version }}_linux_amd64.tar.gz
        ln -sf ghr_v${{ inputs.version }}_linux_amd64/ghr .
